<?php

declare(strict_types=1);

return [

    /*
    |--------------------------------------------------------------------------
    | Default Cache Store
    |--------------------------------------------------------------------------
    | Cache store used by PermissionCacheManager. Set to null to use the
    | default cache store configured in config/cache.php.
    */
    'cache_store' => env('AUTHORIZATION_CACHE_STORE', null),

    /*
    |--------------------------------------------------------------------------
    | Cache TTL
    |--------------------------------------------------------------------------
    | How long (seconds) a resolved snapshot stays in cache. A TTL of 0
    | disables caching entirely; null caches forever (until explicitly
    | invalidated). The cache is also cleared on PermissionCacheInvalidated
    | events emitted by SnapshotRebuildService.
    */
    'cache_ttl' => (int) env('AUTHORIZATION_CACHE_TTL', 600),

    /*
    |--------------------------------------------------------------------------
    | Cache Key Prefix
    |--------------------------------------------------------------------------
    | All cache keys generated by the authorization layer are prefixed.
    | Default prefix produces keys of the form
    | "user_permissions:{userId}:{scopeKey}" when combined with the
    | canonical key builder.
    */
    'cache_prefix' => env('AUTHORIZATION_CACHE_PREFIX', 'user_permissions'),

    /*
    |--------------------------------------------------------------------------
    | Cache Tagging
    |--------------------------------------------------------------------------
    | When enabled and supported by the configured cache store, the cache
    | manager will tag entries so forgetUser()/forgetScope() can flush
    | by tag. Disable for stores that don't support tags (array, database).
    */
    'use_cache_tags' => (bool) env('AUTHORIZATION_USE_TAGS', true),

    /*
    |--------------------------------------------------------------------------
    | Snapshot TTL
    |--------------------------------------------------------------------------
    | Lifetime (seconds) of a snapshot before it is considered expired
    | and triggers an automatic rebuild on next resolve. Independent
    | from cache_ttl — a snapshot can be cached longer than its validity
    | because the rebuild flow checks the expires_at column first.
    */
    'snapshot_ttl' => (int) env('AUTHORIZATION_SNAPSHOT_TTL', 3600),

    /*
    |--------------------------------------------------------------------------
    | Lock Timeout
    |--------------------------------------------------------------------------
    | Maximum wait (seconds) when acquiring an advisory lock during
    | rebuild. Used by SnapshotVersionResolver via DB-specific
    | primitives (pg_advisory_xact_lock, GET_LOCK, BEGIN IMMEDIATE).
    */
    'lock_timeout' => (int) env('AUTHORIZATION_LOCK_TIMEOUT', 5),

    /*
    |--------------------------------------------------------------------------
    | Rebuild Queue
    |--------------------------------------------------------------------------
    | Queue name and connection for BuildSnapshotJob dispatched by
    | observers. Set to null to use the default queue/connection.
    */
    'rebuild_queue' => [
        'connection' => env('AUTHORIZATION_REBUILD_QUEUE_CONNECTION', null),
        'name' => env('AUTHORIZATION_REBUILD_QUEUE_NAME', 'authorization-rebuild'),
        'tries' => (int) env('AUTHORIZATION_REBUILD_TRIES', 3),
        'backoff' => [
            (int) env('AUTHORIZATION_REBUILD_BACKOFF_1', 5),
            (int) env('AUTHORIZATION_REBUILD_BACKOFF_2', 30),
            (int) env('AUTHORIZATION_REBUILD_BACKOFF_3', 120),
        ],
        'timeout' => (int) env('AUTHORIZATION_REBUILD_TIMEOUT', 120),
    ],

    /*
    |--------------------------------------------------------------------------
    | Gate Defaults
    |--------------------------------------------------------------------------
    | When true, AuthorizationGateRegistrar installs a Gate::before()
    | hook that consults AuthorizationManager. Disable to fall back
    | to the policy-only authorization flow.
    */
    'gate_enabled' => (bool) env('AUTHORIZATION_GATE_ENABLED', true),

    /*
    |--------------------------------------------------------------------------
    | Auto-Dispatch
    |--------------------------------------------------------------------------
    | When true, observers attached to permission-bearing models
    | automatically dispatch BuildSnapshotJob. Disable to require
    | explicit dispatch.
    */
    'auto_dispatch_on_change' => (bool) env('AUTHORIZATION_AUTO_DISPATCH', true),

    /*
    |--------------------------------------------------------------------------
    | Debug / Observability
    |--------------------------------------------------------------------------
    | Emit authorization events (SnapshotLoaded, AuthorizationSucceeded,
    | AuthorizationDenied, etc.) when true. Disable in production
    | for hot paths if event listener overhead becomes measurable.
    */
    'emit_events' => (bool) env('AUTHORIZATION_EMIT_EVENTS', true),

];
